name: Automated checks
on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: "Check formatting, linting, and unit tests"
    runs-on: ubuntu-20.04
    steps:
      - name: Run poetry image
        uses: abatilo/actions-poetry@v2
      - uses: actions/checkout@v3
      # Setup a more recent version of Python than default (3.8)
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Run formatter
        run: make format_check
      - name: Run linter
        run: make lint
      - name: Run unit testing
        run: make unit_testing