name: Automated checks
on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: "Check formatting, linting, and unit tests"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run formatter
        run: make format_check
      - name: Run linter
        run: make lint
      - name: Run unit testing
        run: make unit_testing